void StartListing(void);
void EndListing(void);
void NewLine(int);
void echo(char *);
void StartMessage(void);
void EndMessage(void);
void message(char *);
void oops(char *);
void warning(char *);
void ABORT(int, int);
int LineNumber(void);
int ColNumber(void);
